name: build
# This workflow is  triggered on pushes, pull requests to the repository.
on:
  push:
    branches:
      - main
  pull_request:
env:
  version_in_development: v0.0.1
permissions:
  contents: write


jobs:
  build-linux:
    name: build-linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install and build 
        run: |
          wget "https://storage.googleapis.com/engflow-tools-public/reclient/1740689172.tar" -O downloaded_file.tar
          mkdir linux-reclient
          tar -xf downloaded_file.tar -C linux-reclient
          zip -r linux-reclient.zip linux-reclient/
          checksum=$(sha1sum "linux-reclient.zip" | awk '{print $1}')

          echo "## Archives Checksums" > Release.txt
          echo "linux-reclient.zip:$checksum" >> Release.txt
      - name: Create Release
        id: draft_release
        if: github.ref == 'refs/heads/main' || github.head_ref == 'feature/add-script'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          owner: tipi-build 
          repo: distro-reclient
          commitish: main
          tag_name: ${{ env.version_in_development }}
          release_name: ${{ env.version_in_development }} ${{ github.sha }}
          draft: true
          prerelease: true
          body_path: Release.txt
      - name: Upload linux-reclient package
        if: ${{steps.draft_release.outputs.upload_url}}
        id: upload-tipi-reclient-package 
        uses: actions/upload-release-asset@v1
        env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{steps.draft_release.outputs.upload_url}}
          asset_path: ./linux-reclient.zip
          asset_name: linux-reclient.zip
          asset_content_type: application/zip
